name: lizi
description: Cross platform particles library.
version: 0.1.0
homepage: https://github.com/svga/lizi-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
